feat: matka.fi separate park and ride options for car and bike
HSLdevcom/digitransit-ui pull request #4648
Opened 2022-09-30 10:14 UTC by tekoiv

2022-10-03 08:14 UTC, vesameskanen requested changes
- Car parkride switch has disappeared from HSL planner
- Matka planner requests bikeparkride itinerariers even when the respective switch is turned off. This is a computation intensive feature so bikeparkplan should be included only when user asks them.

2022-10-03 08:14 UTC, vesameskanen commented on app/configurations/config.matka.js
> +  includeBikeParkSuggestions: true,
one switch is enough. Use existing showBikeAndParkItineraries.

2022-10-05 08:15 UTC, vesameskanen approved these changes

2022-10-05 08:15 UTC, merged

2023-03-01 12:46 UTC, derhuerst commented on app/component/customizesearch/StreetModeSelectorPanel.js
> +          !config.separatedParkAndRideSwitch && (
I'm not sure I understand the logic, but shouldn't this boolean flag work in the exact opposite way? As in: If the "separated switch" config is `true`, it should show the switch in the UI?
We stumbled upon this while merging changes into the [bbnavi code](https://github.com/bbnavi/digitransit-ui).

2023-03-01 14:22 UTC, vesameskanen commented on app/component/customizesearch/StreetModeSelectorPanel.js
> +          !config.separatedParkAndRideSwitch && (
In reittiopas.hsl.fi, car symbol means park and ride. There is no plain car routing available.
in other planners ( say tampere.digitransit.fi ), car symbol means car routing and there is additional switch for park & ride.

Configuration for e.g. tampere says: 
  // Park and ride and car suggestions separated into two switches                                                                                                                                         
  separatedParkAndRideSwitch: true,

So the switch naming logic seems to be right. The rendering code might be strange as and identical element is used for two different purposes.

Such inconsistency is unfortunate but comes from customer's design.

2023-03-01 14:42 UTC, derhuerst commented on app/component/customizesearch/StreetModeSelectorPanel.js
> +          !config.separatedParkAndRideSwitch && (
Oh, we missed the part below, thanks for pointing this out. In any case, I'd strongly advocate for DRYing the two (quite similar but subtly different) code sections.