Dt 5977
HSLdevcom/digitransit-ui pull request #4868
Opened 2023-10-02 07:04 UTC by sharhio

## Proposed Changes

  - Varely real-time data
  - Rauma data to Varely
  - Varely datat to Matka

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2023-10-03 15:50 UTC, optionsome requested changes
Btw I wonder if there is any reason for us not to include Turku's realtime now as well now in seutuplus?

2023-10-03 15:50 UTC, optionsome commented on app/configurations/config.matka.js
> +    },
Not quite sure what to call this but probably Varsinais-Suomi. Seutu+ is more than this data set (and it sounds slightly weird if you are not aware of what it is and you are interested in alerts around Rovaniemi region for example :D).

2023-10-03 15:50 UTC, optionsome commented on app/configurations/config.varely.js
> +    },
Same as above.

2023-10-04 08:14 UTC, sharhio commented
There is no reason to not add Turku, in fact, it should be added.

2023-10-09 10:23 UTC, merged