Dt-6141: dynamically add city zones if config file flag assembleGeoJsonZones is true
HSLdevcom/digitransit-ui pull request #4935
Opened 2024-01-22 19:10 UTC by Dvun

## Proposed Changes

  - dynamically add city zones if config file flag assembleGeoJsonZones is true

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2024-01-23 06:39 UTC, vesameskanen requested changes
Hyvä alku! Muutama vika pitää vielä korjata.

2024-01-23 06:39 UTC, vesameskanen commented on app/config.js
> +        fetchDataFromGeoJsonUrl(
Tämä ei toimi. Fetch on asynkroninen. Koodin suoritus jatkuu eikä haettu geojson ehdi tulla mukaan lippuvyöhykkeisiin.

2024-01-23 06:39 UTC, vesameskanen commented on app/config.js
> +    if (additionalConfig.default.assembleGeoJsonZones) {
Tämä ei toimi. Konfiguraation pusketaan keskeneräinen kokelma. Kokoa gejson zonet ensin, ja lisää ne vasta kun pyydettyä konfiguraatiota  koostetaan getNamedConfiguration funktiossa.

2024-01-23 06:39 UTC, vesameskanen commented on app/config.js
> +  geoLayers.push({
Tämä menee väärin. Karttavalitsimessa pitää näkyä yksi 'Vyöhykkeet' valinta eikä  yli 10 kpl. Koosta varsinainen geojson geometria yhteen layeriin.

2024-01-31 06:40 UTC, vesameskanen commented on app/component/MapLayersDialogContent.js
> +  updateGeoJsonSettings = (arr, target) => {
En ymmärrä mitä tässä on tarkoitus tapahtua. Komponentissa on kaksi samannimistä funktiota 'updateGeoJsonSettings'. Alempi ylikirjoittaa ensimmäisen. Se, että data haetan monesta urlista ei pitöisi vaikuttaa asetuksiin ollenkaan.

2024-01-31 06:40 UTC, vesameskanen commented on app/server.js
> +    delete config.assembledGeoJsons;
Ihmettelit miksi vyöhykkeet näkyy vain kerran. Syy on tässä: kun vyöhykedata on toimitettu jollekin clientille kerrran, se tuhotaan.

2024-01-31 10:14 UTC, Dvun commented on app/server.js
> +    delete config.assembledGeoJsons;
Totta :)

2024-02-07 06:32 UTC, closed without merging