Navitop fixes part 7: Proper handling of displayed messages
HSLdevcom/digitransit-ui pull request #5115
Opened 2024-10-08 06:34 UTC by Antiik91

## Proposed Changes

  - Users does not see duplicate messages anymore, and dismissed messges are not shown again.

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviContainer.js
> +
store connect is not needed. We do not need to (ands should not) re-render on every position change.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviContainer.js
> +          }
Add this also to realtime leg query.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
> +
This file is getting long, make a little component 'NaviMessage' out of this.

Probably NaviAlerts could also be a new component.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
> -  const { start, realtimeState, to, mode } = nextLeg;
I think 'leg' is a better name for parameter. Somehow being 'next' is irrelevant here.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
>    if (canceled.length > 0) {
id is not common, alerts below can happen parallel. use unique ids.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
>      });
no need to copy the generated alert jsx. Just push it.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
>    const focusRef = useRef(false);
displayNotifs sounds like a switch to put notifications on/off. Maybe visibleNotifications ?

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
> -          notifications={notifications}
WOuld it be more correct to check if visibleNotifications.length >0 instead of nextLeg ?

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
> +        const combined = currentNots.concat(...notifs);
Nofits  - currentnots - displaynotifs -  notifications ... this is very hard to understand.  Please try to refactor. Maybe better names will help. What is 'main' notification, for example?

The code is getting so complicated that we should make all efforts to make it readable again.

2024-10-08 12:08 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
>          <div type="button" className="navitop-arrow">
Time to call 'info' as something more descriptive. Maybe naviTopContent?

2024-10-08 12:22 UTC, vesameskanen commented on app/component/itinerary/NaviTop.js
> +        if (alerts.length > 0) {
This is not correct. Alerts can arise anytime during the trip, not only when current leg changes.

2024-10-08 12:28 UTC, Antiik91 commented on app/component/itinerary/NaviTop.js
>    if (canceled.length > 0) {
This is meant to be a placeholder for now, untill I start to develop correct alert messages. Then we get the proper id's, which are unique.

2024-10-08 13:05 UTC, partisaani requested changes

2024-10-08 13:05 UTC, partisaani commented on app/translations.js
> +    'navileg-mode-citybike': 'Kaupunkipyöriä on asemalla {available} kpl',
In English

2024-10-08 13:05 UTC, partisaani commented on app/translations.js
> +    'navileg-mode-citybike': 'Kaupunkipyöriä on asemalla {available} kpl',
På Svenska

2024-10-08 13:05 UTC, partisaani commented on app/component/itinerary/NaviContainer.js
> +  // eslint-disable-next-line no-unused-vars
Possible leftover

2024-10-09 04:37 UTC, Antiik91 commented on app/component/itinerary/NaviTop.js
>    const focusRef = useRef(false);
Decided to go with activeNotifications. Since those are the notifications that are active as a user perspective.

2024-10-09 10:28 UTC, Antiik91 commented on app/component/itinerary/NaviTop.js
>      });
Reworked around this a bit. Should be more clear now

2024-10-09 10:40 UTC, Antiik91 commented on app/component/itinerary/NaviContainer.js
> +
Got it. I will revert this change, and do the location in another pr, since it will contain more changes regarding it as well.

2024-10-10 06:27 UTC, merged