DT-6532:  In vehicle cards
HSLdevcom/digitransit-ui pull request #5160
Opened 2024-11-12 08:43 UTC by Antiik91

## Proposed Changes

  - Shows in transit information in navigator
  - 

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2024-11-12 09:08 UTC, partisaani requested changes

2024-11-12 09:08 UTC, partisaani commented on app/component/itinerary/NaviCardExtension.js
DRY and KISS; I would refactor the two embedded return values as individual components for reduced complexity of this parent component
```jsx
return (
  <div className="extension">
    <div className="extension-divider" />
    {legType === 'in-transit' ? <TransitLegExtender {...props} /> : <WalkLegExtender {...props} />}
  </div>
)
```
also simplifies testing for all of the three components as for parent you can just sinon.stub() the `*Extender` components with an easily locatable attribute and for the `*Extender`s you can just make sure the component looks as it should with given props

2024-11-12 09:30 UTC, Antiik91 commented on app/component/itinerary/NaviCardExtension.js
Good point, although I reckon that we get a lot of navigation components before we are finished with this, so we don't want to spread too thin here.

I'll take another opinion here as well before I start to refactor this.

2024-11-13 07:45 UTC, vesameskanen requested changes

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCardContainer.js
>      }
Maybe handle leg types like this:

```
export const LEGTYPE = {
  WAIT: 'WAIT',
  MOVE: 'MOVE',
  TRANSIT: 'TRANSIT',
}
```

Add this to  naviUtils and import it from there to other classes which refer to leg types.

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCardContainer.js
>    } else {
There are now 2 separate ways to render wait state. Maybe these formatted messages could be moved to NaviCard? In other words,  leg would not be required prop and legType could be also `ITINERARY_PENDING` and `ITINERARY_ENDED` or something like that.

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCard.js
>    const iconName = legType === 'wait' ? iconMap.WAIT : iconMap[leg.mode];
nextLeg is not required, can be undefined

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCardExtension.js
I don't have a stong opinion about this. I guess we could put all this navi stuff to a sub folder first, and after that start splitting into smaller components.

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCardExtension.js
> +    const count = idx > -1 ? intermediatePlaces.length - idx : 0;
Use Date.now() and legTime.

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviCardExtension.js
> +    const stopCountElement = <span className="realtime"> {count}</span>;
I guess plain `stopCount` isa bit  simpler. We don't have a convention to name jsx snippets as elements.

2024-11-13 07:45 UTC, vesameskanen commented on app/component/itinerary/NaviStack.js
> +  legType: '',
legType does not have logical connection to NaviStack which may contain messages for many legs. I suggest passing the class postfix itself, or maybe handling the vertical offset completely in parent component.

2024-11-13 07:52 UTC, Antiik91 commented on app/component/itinerary/NaviCardExtension.js
I'll create the subfolder in this pr. And after I start refactoring the wait leg, I'll get back to this.

2024-11-13 07:53 UTC, Antiik91 commented on app/component/itinerary/NaviCardContainer.js
>    } else {
This will be considered in the next PR, where I'll refactor the wait leg

2024-11-14 08:27 UTC, vesameskanen approved these changes

2024-11-14 08:27 UTC, merged