DT-6533 Improved navigator and local storage cooperation
HSLdevcom/digitransit-ui pull request #5162
Opened 2024-11-12 21:20 UTC by partisaani

## Proposed Changes
Navigator is now more context aware:
  - If `from`, `to`, `time`, `arriveBy` and `hash` parameters are identical to those of the stored journey
    - Traversing to `ItineraryPage` detail view will automatically trigger the Navigator journey.
  - If `from`, `to`, `time` and `arriveBy` parameters are identical to those of the stored journey
    - Traversing to `ItineraryPage` list view does not necessarily purge the stored itinerary from memory.
      - Local storage entry is purged if user navigates to list view from active navigator journey either by using the arrow icon or by browsing back using browser history
    - Traversing to `ItineraryPage` detail view does not purge the stored itinerary from memory, but a Navigator journey is not triggered
  - If any of the parameters is different
    - Traversing to `ItineraryPage` list view or detail view will purge the stored Navigator journey from local storage

## Pull Request Check List

  - [ ] A reasonable set of unit tests is included
  - [x] Console does not show new warnings/errors
  - [x] Changes are documented or they are self explanatory
  - [x] This pull request does not have any merge conflicts
  - [x] All existing tests pass in CI build

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2024-11-12 21:27 UTC, partisaani commented on app/component/itinerary/ItineraryDetails.js
Whitespace and format changes only

2024-11-13 06:17 UTC, Antiik91 commented on app/component/itinerary/ItineraryPage.js
> +  const isMatchingParams = (storedParams, shouldCompareHash) => {
I think these should be moved in some util file if possible, in order not to bloat the ItineraryPage more than necessary.

2024-11-13 10:31 UTC, Antiik91 approved these changes

2024-11-13 11:00 UTC, vesameskanen requested changes
Note that when you open itinerary detaul view of a  bike and transit itinerary, hash is not itinerary index. It can be found from secondaryHash.

As far as I can see, we need to 'auto relaunch' navigation only in one occasion: page reloading. This is handled in useEffect [].

2024-11-13 11:00 UTC, vesameskanen commented on app/component/itinerary/ItineraryPageUtils.js
> +    storedParams.arriveBy === match?.location?.query?.arriveBy
no need for match?, it is tested in the beginning of the function. Actually, can match be undefined?

2024-11-13 11:00 UTC, vesameskanen commented on app/component/itinerary/StartNavi.js
> +        index: match.params.hash,
Unfortunately, we have to deal with secondaryHash as well.

2024-11-13 11:00 UTC, vesameskanen commented on app/component/itinerary/ItineraryPage.js
> +    }
I think you need something like this here:
 ```
 if (isStoredItineraryRelevant(match)) { 
    setnavigation(true);
} else {
  clearLatestNavigatorItinerary();
}
```
relevance testing can handle all  hash checking logic

2024-11-13 11:00 UTC, vesameskanen commented on app/component/itinerary/ItineraryPage.js
>    }, [
I don't think this is necessary. Itinerary search parameter change never triggers navi mode.

2024-11-13 11:00 UTC, vesameskanen commented on app/component/itinerary/ItineraryPage.js
Not necessary. Hash change should not trigger navi mode.

2024-11-13 11:19 UTC, partisaani commented on app/component/itinerary/StartNavi.js
> +        index: match.params.hash,
Will be added.

2024-11-13 11:23 UTC, partisaani commented on app/component/itinerary/ItineraryPageUtils.js
> +    storedParams.arriveBy === match?.location?.query?.arriveBy
It is likely match cannot be undefined, but I don't think being prepared for such occasion is detrimental

2024-11-13 11:24 UTC, partisaani commented on app/component/itinerary/ItineraryPage.js
Will remove

2024-11-13 11:24 UTC, partisaani commented on app/component/itinerary/ItineraryPage.js
>    }, [
Will remove

2024-11-13 12:26 UTC, partisaani commented
> As far as I can see, we need to 'auto relaunch' navigation only in one occasion: page reloading. This is handled in useEffect [].

Will refactor with this in mind. For possible future reference the current implementation enables the user to browse between itineraries and their detail views. Only explicit backtrack from an initiated journey or a change in `from`, `to`, `time` or `arriveBy` params signal to purge the stored itinerary.

2024-11-13 13:36 UTC, vesameskanen requested changes

2024-11-13 13:36 UTC, vesameskanen commented on app/component/itinerary/ItineraryPageUtils.js
> +};
- last condition is apparently wrong, shoudl be ( params.index == secondHash || params.index == hash )
- would it be easier and safer to save hash and secondHash and compare both ?
- let code crash if match params is not defined. unnecessary validation to keep code running  although everyhing is all wrong is not wise

2024-11-13 20:09 UTC, partisaani commented on app/component/itinerary/ItineraryPageUtils.js
> +};
Refactored and fixed.

2024-11-14 05:14 UTC, vesameskanen approved these changes
very good

2024-11-14 05:14 UTC, merged