DT-6548: Wait card
HSLdevcom/digitransit-ui pull request #5169
Opened 2024-11-19 12:30 UTC by Antiik91

## Proposed Changes

  - Refactored wait car to match current design
  - Refactored how the top position of navistack is determined. Calculate it instead of using ever growing number of classes.
  - Refactored the card style to match current desing
  - Switched navi-expand icon to match current desing.

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2024-11-20 11:01 UTC, vesameskanen requested changes
I found only some minor issues that coudl be changed.

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviCard.js
>    if (legType === LEGTYPE.TRANSIT) {
This logic leaks. WAIT leg gets id navileg-undefined. Maybe harmless, but these if conditions are bit hard to understand. Please rearrange.

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviCardContainer.js
> +  });
Really a minor thing, but next leg search could be little func just like getFirstLastLegs(). It is done twice in this file.

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviCardExtension.js
> +            mode={vehicleMode.toLowerCase()}
Why this change? at least HSL stops have sometimes wrong mode data.

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviCardExtension.js
> +    const hs = headsign || trip?.tripHeadsign;
Transit legs always include trip, no need for ?

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviInstructions.js
>    const [fadeOut, setFadeOut] = useState(false);
incorrect proptypes require both legs

2024-11-20 11:01 UTC, vesameskanen commented on app/component/itinerary/navigator/NaviInstructions.js
> +    const color = route?.color ? route.color : 'currentColor';
route.color || 'currentColor'

2024-11-20 11:10 UTC, Antiik91 commented on app/component/itinerary/navigator/NaviCardExtension.js
> +            mode={vehicleMode.toLowerCase()}
There was an issue with the leg.mode was not shown, I'll revisit on this and see if it's still the case, and will fix.

2024-11-21 06:33 UTC, vesameskanen approved these changes

2024-11-21 06:33 UTC, merged